# Generated by Django 4.2.7 on 2024-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Photo', models.FileField(default=None, max_length=350, null=True, upload_to='image/')),
            ],
        ),
    ]
